### ISSUE TITLE
Using third party libraries

### ISSUE THREAD

**Issue by shenxiangzhuang** [asiffer/mkdocs-onecompiler-plugin#1]
Is there any chance that we can use the plugin to install some package from pypi and run it in the code block? That will be awesome, in this way, we can illustrate the library by running the code in the package's documentation.

**Comment by asiffer** [comment]
Unfortunately, it only depends on onecompiler... But currently, third party libraries are very limited and you cannot dl your own (maybe with a premium account but I am not sure). Obviously, it would be awesome! I think the main hindrance is security: it would be hard to manage third party package execution on a remote server.

**Comment by shenxiangzhuang** [comment]
Thank you for you timely reply! I agree that safety is the main concern. 

Just a mention, I'm currently using [react-py](https://elilambnz.github.io/react-py/), which works fine with third party libraries but need some js/tsx code to run it. I not good at js/tsx, so is the reason that I try to find other tools to do it.

Feel free to close the issue and thank you again~
